_extends: .github
name-template: $NEXT_PATCH_VERSION
tag-template: robot-$NEXT_VERSION_VERSION
version-template: $MAJOR.$MINOR.$PATCH
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'maintenance'
exclude-labels:
  - 'skip-changelog'